// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moo_Arvelous_Coders.Models;

#nullable disable

namespace Moo_Arvelous_Coders.Migrations
{
    [DbContext(typeof(MooArvelousDbContext))]
    [Migration("20251001123704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Buyer", b =>
                {
                    b.Property<int>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuyerId"));

                    b.Property<string>("BConfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BfirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bidnumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BphoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuyerId");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Cattle", b =>
                {
                    b.Property<int>("CattleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CattleId"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfDeath")
                        .HasColumnType("date");

                    b.Property<int?>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Health")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("HerdId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("CattleId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("HerdId");

                    b.ToTable("Cattles");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattleHealthRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int?>("CattleId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<string>("TreatmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordId");

                    b.HasIndex("CattleId");

                    b.ToTable("CattleHealthRecords");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattlePhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int?>("CattleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotoId");

                    b.HasIndex("CattleId");

                    b.ToTable("CattlePhotos");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattleSaleRecord", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int");

                    b.Property<int?>("CattleId")
                        .HasColumnType("int");

                    b.Property<int?>("FarmerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SaleId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CattleId");

                    b.HasIndex("FarmerId");

                    b.ToTable("CattleSaleRecords");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Farm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmId"));

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("FarmSize")
                        .HasColumnType("float");

                    b.Property<int?>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PriceBought")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("FarmId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmerId"));

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Idnumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FarmerId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("Idnumber")
                        .IsUnique();

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Herd", b =>
                {
                    b.Property<int>("HerdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HerdId"));

                    b.Property<string>("Bull")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cattle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FarmId")
                        .HasColumnType("int");

                    b.Property<int?>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("HerdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Herdsize")
                        .HasColumnType("int");

                    b.HasKey("HerdId");

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Herds");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.HerdComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("FarmerId")
                        .HasColumnType("int");

                    b.Property<int>("HerdId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("HerdId");

                    b.ToTable("HerdComments");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Cattle", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Farmer", "Farmer")
                        .WithMany("Cattles")
                        .HasForeignKey("FarmerId");

                    b.HasOne("Moo_Arvelous_Coders.Models.Herd", "Herd")
                        .WithMany("Cattles")
                        .HasForeignKey("HerdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Farmer");

                    b.Navigation("Herd");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattleHealthRecord", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Cattle", "Cattle")
                        .WithMany("CattleHealthRecords")
                        .HasForeignKey("CattleId");

                    b.Navigation("Cattle");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattlePhoto", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Cattle", "Cattle")
                        .WithMany("CattlePhotos")
                        .HasForeignKey("CattleId");

                    b.Navigation("Cattle");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattleSaleRecord", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Buyer", "Buyer")
                        .WithMany("CattleSaleRecords")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Moo_Arvelous_Coders.Models.Cattle", "Cattle")
                        .WithMany("CattleSaleRecords")
                        .HasForeignKey("CattleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Moo_Arvelous_Coders.Models.Farmer", "Farmer")
                        .WithMany("CattleSaleRecords")
                        .HasForeignKey("FarmerId");

                    b.Navigation("Buyer");

                    b.Navigation("Cattle");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Farm", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Farmer", "Farmer")
                        .WithMany("Farms")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Herd", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Farm", "Farm")
                        .WithMany("Herds")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Moo_Arvelous_Coders.Models.Farmer", "Farmer")
                        .WithMany("Herds")
                        .HasForeignKey("FarmerId");

                    b.Navigation("Farm");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.HerdComment", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Farmer", "Farmer")
                        .WithMany("HerdComments")
                        .HasForeignKey("FarmerId");

                    b.HasOne("Moo_Arvelous_Coders.Models.Herd", "Herd")
                        .WithMany("HerdComments")
                        .HasForeignKey("HerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");

                    b.Navigation("Herd");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Buyer", b =>
                {
                    b.Navigation("CattleSaleRecords");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Cattle", b =>
                {
                    b.Navigation("CattleHealthRecords");

                    b.Navigation("CattlePhotos");

                    b.Navigation("CattleSaleRecords");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Farm", b =>
                {
                    b.Navigation("Herds");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Farmer", b =>
                {
                    b.Navigation("CattleSaleRecords");

                    b.Navigation("Cattles");

                    b.Navigation("Farms");

                    b.Navigation("HerdComments");

                    b.Navigation("Herds");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Herd", b =>
                {
                    b.Navigation("Cattles");

                    b.Navigation("HerdComments");
                });
#pragma warning restore 612, 618
        }
    }
}
