// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moo_Arvelous_Coders.Models;

#nullable disable

namespace Moo_Arvelous_Coders.Migrations
{
    [DbContext(typeof(MooArvelousDbContext))]
    partial class MooArvelousDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Buyer", b =>
                {
                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("BuyerID");

                    b.Property<string>("Bemail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BEmail");

                    b.Property<string>("BfirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BFirstName");

                    b.Property<string>("Bidnumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BIDNumber");

                    b.Property<string>("BlastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BLastName");

                    b.Property<string>("BphoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BPhoneNumber");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BuyerId")
                        .HasName("PK__Buyer__4B81C1CA078A2677");

                    b.HasIndex(new[] { "Bidnumber" }, "UQ__Buyer__218A515C8481D745")
                        .IsUnique()
                        .HasFilter("[BIDNumber] IS NOT NULL");

                    b.ToTable("Buyer", (string)null);
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Cattle", b =>
                {
                    b.Property<string>("CattleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CattleID");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfDeath")
                        .HasColumnType("date");

                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FarmerID");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Health")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HerdId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("HerdID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CattleId")
                        .HasName("PK__Cattle__E375C63CBAD731FD");

                    b.HasIndex("FarmerId");

                    b.HasIndex("HerdId");

                    b.ToTable("Cattle", (string)null);
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattleHealthRecord", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RecordID");

                    b.Property<string>("CattleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CattleID");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<string>("TreatmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RecordId")
                        .HasName("PK__CattleHe__FBDF78C921E20F58");

                    b.HasIndex("CattleId");

                    b.ToTable("CattleHealthRecord", (string)null);
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattlePhoto", b =>
                {
                    b.Property<string>("PhotoId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PhotoID");

                    b.Property<string>("CattleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CattleID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PhotoURL");

                    b.HasKey("PhotoId")
                        .HasName("PK__CattlePh__21B7B5826EA21737");

                    b.HasIndex("CattleId");

                    b.ToTable("CattlePhoto", (string)null);
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattleSaleRecord", b =>
                {
                    b.Property<string>("SaleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SaleID");

                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("BuyerID");

                    b.Property<string>("CattleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CattleID");

                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FarmerID");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("SaleId")
                        .HasName("PK__CattleSa__1EE3C41F136A9DDC");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CattleId");

                    b.HasIndex("FarmerId");

                    b.ToTable("CattleSaleRecord", (string)null);
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Farm", b =>
                {
                    b.Property<string>("FarmId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FarmID");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("FarmSize")
                        .HasColumnType("float");

                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FarmerID");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PriceBought")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("FarmId")
                        .HasName("PK__Farm__ED7BBA99F98F561A");

                    b.HasIndex("FarmerId");

                    b.ToTable("Farm", (string)null);
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Farmer", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FarmerID");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Idnumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("IDNumber");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FarmerId")
                        .HasName("PK__Farmer__731B88E8CB2BC6CA");

                    b.HasIndex(new[] { "EmailAddress" }, "UQ__Farmer__49A147408D2FB0FE")
                        .IsUnique();

                    b.HasIndex(new[] { "Idnumber" }, "UQ__Farmer__564DB08AE2C54990")
                        .IsUnique();

                    b.ToTable("Farmer", (string)null);
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Herd", b =>
                {
                    b.Property<string>("HerdId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("HerdID");

                    b.Property<string>("Bull")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cattle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FarmId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FarmID");

                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FarmerID");

                    b.Property<string>("HerdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Herdsize")
                        .HasColumnType("int");

                    b.HasKey("HerdId")
                        .HasName("PK__Herd__0889874A8A2B7728");

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Herd", (string)null);
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.HerdComment", b =>
                {
                    b.Property<string>("CommentId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CommentID");

                    b.Property<string>("CommentDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FarmerID");

                    b.Property<string>("HerdId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("HerdID");

                    b.HasKey("CommentId")
                        .HasName("PK__HerdComm__C3B4DFAA66060F54");

                    b.HasIndex("FarmerId");

                    b.HasIndex("HerdId");

                    b.ToTable("HerdComment", (string)null);
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Cattle", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Farmer", "Farmer")
                        .WithMany("Cattles")
                        .HasForeignKey("FarmerId")
                        .HasConstraintName("FK__Cattle__FarmerID__44FF419A");

                    b.HasOne("Moo_Arvelous_Coders.Models.Herd", "Herd")
                        .WithMany("Cattles")
                        .HasForeignKey("HerdId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Cattle__HerdID__440B1D61");

                    b.Navigation("Farmer");

                    b.Navigation("Herd");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattleHealthRecord", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Cattle", "Cattle")
                        .WithMany("CattleHealthRecords")
                        .HasForeignKey("CattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__CattleHea__Cattl__4AB81AF0");

                    b.Navigation("Cattle");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattlePhoto", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Cattle", "Cattle")
                        .WithMany("CattlePhotos")
                        .HasForeignKey("CattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__CattlePho__Cattl__47DBAE45");

                    b.Navigation("Cattle");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.CattleSaleRecord", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Buyer", "Buyer")
                        .WithMany("CattleSaleRecords")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__CattleSal__Buyer__52593CB8");

                    b.HasOne("Moo_Arvelous_Coders.Models.Cattle", "Cattle")
                        .WithMany("CattleSaleRecords")
                        .HasForeignKey("CattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__CattleSal__Cattl__5070F446");

                    b.HasOne("Moo_Arvelous_Coders.Models.Farmer", "Farmer")
                        .WithMany("CattleSaleRecords")
                        .HasForeignKey("FarmerId")
                        .HasConstraintName("FK__CattleSal__Farme__5165187F");

                    b.Navigation("Buyer");

                    b.Navigation("Cattle");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Farm", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Farmer", "Farmer")
                        .WithMany("Farms")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Farm__FarmerID__3B75D760");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Herd", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Farm", "Farm")
                        .WithMany("Herds")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Herd__FarmID__3E52440B");

                    b.HasOne("Moo_Arvelous_Coders.Models.Farmer", "Farmer")
                        .WithMany("Herds")
                        .HasForeignKey("FarmerId")
                        .HasConstraintName("FK__Herd__FarmerID__3F466844");

                    b.Navigation("Farm");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.HerdComment", b =>
                {
                    b.HasOne("Moo_Arvelous_Coders.Models.Farmer", "Farmer")
                        .WithMany("HerdComments")
                        .HasForeignKey("FarmerId")
                        .HasConstraintName("FK__HerdComme__Farme__5629CD9C");

                    b.HasOne("Moo_Arvelous_Coders.Models.Herd", "Herd")
                        .WithMany("HerdComments")
                        .HasForeignKey("HerdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HerdComme__HerdI__5535A963");

                    b.Navigation("Farmer");

                    b.Navigation("Herd");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Buyer", b =>
                {
                    b.Navigation("CattleSaleRecords");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Cattle", b =>
                {
                    b.Navigation("CattleHealthRecords");

                    b.Navigation("CattlePhotos");

                    b.Navigation("CattleSaleRecords");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Farm", b =>
                {
                    b.Navigation("Herds");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Farmer", b =>
                {
                    b.Navigation("CattleSaleRecords");

                    b.Navigation("Cattles");

                    b.Navigation("Farms");

                    b.Navigation("HerdComments");

                    b.Navigation("Herds");
                });

            modelBuilder.Entity("Moo_Arvelous_Coders.Models.Herd", b =>
                {
                    b.Navigation("Cattles");

                    b.Navigation("HerdComments");
                });
#pragma warning restore 612, 618
        }
    }
}
